package com.app.nexio.user.model;

public enum University {
    NEW_BULGARIAN_UNIVERSITY,
    MEDICAL_UNIVERSITY_OF_SOFIA,
    SOFIA_UNIVERSITY_ST_KLIMENT_OHRIDSKI,
    TECHNICAL_UNIVERSITY_OF_SOFIA,
    UNIVERSITY_OF_NATIONAL_AND_WORLD_ECONOMY,
    UNIVERSITY_OF_ARCHITECTURE_CIVIL_ENG_AND_GEODESY
}

